rbac:
  useDefault: true
  serviceAccountName: hpa-scale-to-zero

app:
  hpaSelector: spscommerce.com/scaleToZero=true
  port: 9000

pod:
  repository: ""
  version: ""
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi
  affinity: {}
  tolerations: []

grafana:
  useDefault: true
  dashboard: "files/grafana.json"

prometheus:
  useDefault: true
  selector: cluster-prometheus
  labels: {}
  annotations: {}
  alertGroups:
    - name: ScaleToZeroPanic
      alerts:
        - name: ScaleToZeroPanic
          for: 1m
          additionalLabels: 
            severity: critical
          additionalAnnotations: 
            summary: scale-to-zero panicked
            description: panic occurred
          expression: |-
            delta(scale_to_zero_panics{service="kube-hpa-scale-to-zero"}[2m])>0
    - name: ScaleToZeroMetricError
      alerts:
        - name: ScaleToZeroMetricError
          for: 3m
          additionalLabels: 
            severity: warning
          additionalAnnotations: 
            summary: scale-to-zero unable to determine if scaling is required
            description: Unable to process one of HPA metrics        
          expression: |- 
            delta(scale_to_zero_errors{service="kube-hpa-scale-to-zero", type!="scaling"}[2m])>0"
    - name: ScaleToZeroScalingError
      alerts:
        - name: ScaleToZeroScalingError
          for: 1m
          additionalLabels:
            severity: critical
          additionalAnnotations:
            summary: scale-to-zero unable to scale 
            description: HPA target should be scaled, but error occurred         
          expression: |- 
            delta(scale_to_zero_errors{service="kube-hpa-scale-to-zero", type="scaling"}[2m])>0"      

