rbac:
  useDefault: true
  serviceAccountName: hpa-scale-to-zero

app:
  hpaSelector: spscommerce.com/scaleToZero=true
  port: 9000

pod:
  repository: "<path to your OCI repository>"
  version: "<tag>"
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

grafana:
  useDefault: true
  dashboard: "files/grafana.json"

prometheus:
  useDefault: true
  selector: cluster-prometheus
  alerts:
    labels: {}
    panics:
      useDefault: true
      severity: critical
      description: Unable to proceed with HPA because of panic.
      for: 1m
      labels: {}
    metricErrors:
      useDefault: true
      severity: warning
      description: Unable to process one of HPA metrics.
      for: 3m
      labels: {}
    scalingErrors:
      useDefault: true
      severity: critical
      description: HPA target should be scaled, but error occurred.
      for: 1m
      labels: {}


