{
 "title": "ScaleToZero",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Panics",
   "type": "stat",
   "description": "amount of panics",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(scale_to_zero_panics{service=\"kube-hpa-scale-to-zero\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HPAs",
   "type": "stat",
   "description": "Amount of HPAs that are monitored by scale-to-zero service",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scale_to_zero_total_hpa{service=\"kube-hpa-scale-to-zero\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Problems with scaling",
   "type": "timeseries",
   "description": "is there any metric-related errors. 0 = good, everything else = bad",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "clamp(delta(scale_to_zero_errors{service=\"kube-hpa-scale-to-zero\", type=\"scaling\"}[$__rate_interval]),0,1)",
     "legendFormat": "{{target_namespace}}.{{target_hpa}}"
    }
   ]
  },
  {
   "title": "Custom metric errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "clamp(delta(scale_to_zero_errors{service=\"kube-hpa-scale-to-zero\", type=\"custom_metric\"}[2m]),0,1)",
     "legendFormat": "{{target_namespace}}.{{target_hpa}}"
    }
   ]
  },
  {
   "title": "External metric errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "clamp(delta(scale_to_zero_errors{service=\"kube-hpa-scale-to-zero\", type=\"external_metric\"}[2m]),0,1)",
     "legendFormat": "{{target_namespace}}.{{target_hpa}}"
    }
   ]
  },
  {
   "title": "NotSupported errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "clamp(delta(scale_to_zero_errors{service=\"kube-hpa-scale-to-zero\", type=\"not_supported\"}[2m]),0,1)",
     "legendFormat": "{{target_namespace}}.{{target_hpa}}"
    }
   ]
  },
  {
   "title": "Unexpected HPA state errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "clamp(delta(scale_to_zero_errors{service=\"kube-hpa-scale-to-zero\", type=\"hpa_state\"}[2m]),0,1)",
     "legendFormat": "{{target_namespace}}.{{target_hpa}}"
    }
   ]
  },
  { "title": "Scaling Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Scale ups",
   "type": "timeseries",
   "description": "amount of scale ups",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "delta(scale_to_zero_events{service=\"kube-hpa-scale-to-zero\", type=\"scale_up\"}[$__rate_interval])",
     "legendFormat": "{{target_namespace}}.{{target_hpa}}"
    }
   ]
  },
  {
   "title": "Scale Down",
   "type": "timeseries",
   "description": "amount of scale downs",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "delta(scale_to_zero_events{service=\"kube-hpa-scale-to-zero\", type=\"scale_dowm\"}[$__rate_interval])",
     "legendFormat": "{{target_namespace}}.{{target_hpa}}"
    }
   ]
  }
 ]
}