{{ if .Values.prometheus.useDefault }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "kube-hpa-scale-to-zero.labels" . | nindent 4 }}
    app: {{ include "kube-hpa-scale-to-zero.fullname" . }}
    prometheus: {{ .Values.prometheus.selector }}
    release: prom
  name: {{ include "kube-hpa-scale-to-zero.fullname" . }}
spec:
  endpoints:
    - interval: 10s
      path: /metrics
      targetPort: {{ .Values.app.port }}
      port: metrics
  selector:
    matchLabels:
      {{- include "kube-hpa-scale-to-zero.selectorLabels" . | nindent 6 }}
      app: {{ include "kube-hpa-scale-to-zero.fullname" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-scale-to-zero
  labels:
    {{- include "kube-hpa-scale-to-zero.labels" . | nindent 4 }}
    prometheus: {{ .Values.prometheus.selector }}
spec:
  groups:
    {{ range $alertGroup := .Values.prometheus.alertGroups }}
    - name: {{ $alertGroup.name }}
      rules:
        {{ range $alert := $alertGroup.alerts }}
        - alert: {{$alert.name}}
          expr: {{ $alert.expression }}
          for: {{ $alert.for }}
          labels:
            {{- if $.Values.prometheus.labels }}
            {{- toYaml $.Values.prometheus.labels | nindent 12 }}
            {{- end }}
            {{- if $alert.additionalLabels }}
            {{- toYaml $alert.additionalLabels | nindent 12 }}
            {{- end }}
          annotations:
            {{- if $.Values.prometheus.annotations }}
            {{- toYaml $.Values.prometheus.annotations | nindent 12 }}
            {{- end }}
            {{- if $alert.additionalAnnotations }}
            {{- toYaml $alert.additionalAnnotations | nindent 12 }}
            {{- end }}            
        {{ end }}
    {{ end }}
{{ end }}