{{ if .Values.rbac.useDefault }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    {{- include "kube-hpa-scale-to-zero.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["custom.metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get"]
  - apiGroups: ["external.metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    {{- include "kube-hpa-scale-to-zero.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.serviceAccountName}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    {{- include "kube-hpa-scale-to-zero.labels" . | nindent 4 }}

{{ end }}