---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scale-to-zero-demo
  name: scale-to-zero-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: scale-to-zero-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scale-to-zero-demo
    spec:
      containers:
      - image: nginx:1.29.1
        imagePullPolicy: Always
        name: scale-to-zero-demo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File


---
apiVersion: v1
kind: Service
metadata:
  name: scale-to-zero-demo-service
spec:
  selector:
    app: scale-to-zero-demo
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scale-to-zero-demo-hpa
  labels:
    scaletozero.spscommerce.com/watch: "true"
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
    scaleDown:
      stabilizationWindowSeconds: 300
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scale-to-zero-demo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: scale-to-zero-demo-prometheus-data-generator
      metric:
        name: scale_to_zero_demo_replica_count
        selector:
            matchLabels:
                { 
                    facet: "1", 
                    service: "scale-to-zero-demo-prometheus-data-generator"
                }
      target:
        type: Value
        value: "1"