---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scale-to-zero-demo-prometheus-data-generator
data:
  config.yml: |
    ---
    config:
      - name: scale_to_zero_demo_replica_count
        description: The number of we wanna have.
        type: gauge
        labels: [deployment, facet]
        sequence:
          - time: 5
            eval_time: 60
            values: 2-3
            operation: set
            labels:
              deployment: scale-to-zero-demo-prometheus-data-generator
              facet: 1
          - time: 5
            eval_time: 60
            values: 2-3
            operation: set
            labels:
              deployment: scale-to-zero-demo-prometheus-data-generator
              facet: 2    
      - name: scale_to_zero_demo_replica_count_external
        description: The number of we wanna have.
        type: gauge
        labels: [namespace, exported_job]
        sequence:
          - time: 5
            eval_time: 60 
            values: 2-3
            operation: set
            labels:
              namespace: default
              exported_job: external-metrics-generator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scale-to-zero-demo-prometheus-data-generator
  name: scale-to-zero-demo-prometheus-data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-to-zero-demo-prometheus-data-generator
  template:
    metadata:
      labels:
        app: scale-to-zero-demo-prometheus-data-generator
    spec:
      containers:
      - image: littleangryclouds/prometheus-data-generator:0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: PDG_CONFIG
          value: /pdg/config.yml
        name: scale-to-zero-demo-prometheus-data-generator
        ports:
        - containerPort: 9000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /pdg/
      - image: jimmidyson/configmap-reload:v0.9.0
        args:
        - -webhook-url=http://localhost:9000/-/reload
        - -volume-dir=/pdg/
        - -webhook-method=GET
        name: config-reloader
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
          requests:
            cpu: 5m
            memory: 10Mi
        volumeMounts:
        - name: config
          mountPath: /pdg/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: scale-to-zero-demo-prometheus-data-generator
---
apiVersion: v1
kind: Service
metadata:
  name: scale-to-zero-demo-prometheus-data-generator
  labels:
    app: scale-to-zero-demo-prometheus-data-generator
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: metrics
  selector:
    app: scale-to-zero-demo-prometheus-data-generator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: scale-to-zero-demo-prometheus-data-generator
    release: prometheus
  name: scale-to-zero-demo-prometheus-data-generator
spec:
  endpoints:
  - interval: 10s
    path: /metrics/
    port: metrics
  selector:
    matchLabels:
      app: scale-to-zero-demo-prometheus-data-generator