# https://github.com/helm/charts/tree/master/stable/prometheus-adapter
prometheus:
  url: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local
  port: 9090

# https://github.com/helm/charts/tree/master/stable/prometheus-adapter
rules:
  default: false
  custom:
    - seriesQuery: 'scale_to_zero_demo_replica_count{deployment!=""}'
      seriesFilters: []
      resources:
        overrides:
          namespace:
            resource: namespace
          deployment:
            resource: deployment
      metricsQuery: clamp(<<.Series>>{<<.LabelMatchers>>},0,1000)
