name: UpdateChart
run-name: update chart
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - .github/**
      - demo/**
      - LICENCE
      - Readme.md
      - .gitignore
      - .dockerignore
      - .releaserc.yaml

jobs:
  push-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog
            @google/semantic-release-replace-plugin
            conventional-changelog-conventionalcommits